# Configuración de Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.xhvrwzvwoxdlczixbkbm&password=u7cW7dYEvXJOZTBj
spring.datasource.username=postgres.xhvrwzvwoxdlczixbkbm
spring.datasource.password=u7cW7dYEvXJOZTBj
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html